### ISSUE TITLE
[TRACKER] Roadmap

### ISSUE THREAD

**Issue by fire** [godot-extended-libraries/lottie#1]
- [x] Import as image animations
- [x] Import single frame as 2d image
- [x] Import all frames as animation

**Comment by fire** [comment]
Done.
